// Code generated by protoc-gen-go.
// source: cluster.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	cluster.proto

It has these top-level messages:
	Negotiate
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Negotiate struct {
	Magic            *string  `protobuf:"bytes,1,req,name=magic" json:"magic,omitempty"`
	Version          *int32   `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	Options          []string `protobuf:"bytes,3,rep,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Negotiate) Reset()         { *m = Negotiate{} }
func (m *Negotiate) String() string { return proto.CompactTextString(m) }
func (*Negotiate) ProtoMessage()    {}

func (m *Negotiate) GetMagic() string {
	if m != nil && m.Magic != nil {
		return *m.Magic
	}
	return ""
}

func (m *Negotiate) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Negotiate) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}
